GRANT SELECT ON CLIENT , EMPLACEMENT , PENSION TO rmarty , mlassaire , kcassaigne , lbrauman , abeaunoir , ypaumard , jduguet , alawson ;

GRANT SELECT ON CLIENT , EMPLACEMENT TO jhuis ;

GRANT SELECT ON CLIENT , EMPLACEMENT TO elehmann , pcosta ;

GRANT SELECT ON CLIENT , EMPLACEMENT TO mcohen ;

GRANT SELECT , INSERT , UPDATE , DELETE ON CLIENT , DETERMINE TO htrusco , sborelli ;

GRANT SELECT ON EMPLACEMENT , PENSION TO htrusco , sborelli ; 

GRANT SELECT , INSERT , UPDATE , DELETE ON CLIENT , DETERMINE , EMPLACEMENT , PENSION  TO ftrusco ;

GRANT ALL PRIVILEGES ON CLIENT , DETERMINE , EMPLACEMENT , PENSION TO maintenance ;

GRANT SELECT ON CLIENT , PENSION to hjoin ;

